Merge consul and instance-recovery features
canonical/snap-openstack pull request #356
Opened 2024-11-15 00:30 UTC by MylesJP

Summary of changes
- Move consul-related files into /instance-recovery
- Update consul unit tests to be general instance-recovery tests
- Remove 'sunbeam enable consul' function test from build-snap.yaml

2024-11-15 09:13 UTC, hemanthnakkina requested changes
My understanding, consul.py should constitute helper class to provide necessary information to InstanceRecoveryFeature class  + Consul classes related plans/Steps

The ConsulFeature class need not be a derived class of OpenStackControlPlaneFeature as it is more of a helper class. Do you see a need for the class to be a derived class?
If functions in ConsulFeature requires certain information like manifest, config etc they can be passed by the calling function in InstanceRecoveryFeature.
 
There are certain functions in consul.py that are not called by InstanceRecoveryFeature class and so can be removed like enable_command, disable_command.

2024-11-20 07:50 UTC, hemanthnakkina commented
> @hemanthnakkina I updated the ConsulFeature object to consist of static methods that are simply called by InstanceRecovery when needed. I am noticing that the "Feature consul not found" message is still appearing then running `sunbeam enable instance-recovery`. Any thoughts on why this might be? I have this marked as draft for now.

Maybe its because manifests/edge.yml is not updated. Remove consul feature and add necessary charms under `instance-recovery`.
`instance-recovery` feature should not exist in rest of the yml files in manifest as this feature is supported only in edge.

2024-11-21 07:51 UTC, gboutry requested changes
Please, run the linter locally and apply the changes

2024-11-25 02:51 UTC, hemanthnakkina commented on sunbeam-python/sunbeam/features/instance_recovery/feature.py
> +        return consul_tfvar_map | instance_recovery_tfvar_map
Need a deep copy of the dicts here. Currently consul_tfvar_map is overrided which leads to consul-channel not set in terraform tfvars.

2024-11-26 04:34 UTC, hemanthnakkina approved these changes

2024-11-26 08:26 UTC, gboutry approved these changes

2024-11-26 08:27 UTC, merged

2024-11-26 08:27 UTC, gboutry commented
LGTM, nice work!