Remove microk8s from sunbeam
canonical/snap-openstack pull request #374
Opened 2024-12-05 17:00 UTC by MylesJP

2024-12-10 08:56 UTC, gboutry approved these changes
This is looking good, just need a rebase, you can take these comments into consideration then

2024-12-11 00:46 UTC, hemanthnakkina requested changes

2024-12-11 00:46 UTC, hemanthnakkina commented on .github/workflows/test-snap.yml
> +        description: Specify k8s provider
This job is created to test k8s and microk8s. With only one provider now, we can remove this job.

2024-12-11 00:46 UTC, hemanthnakkina commented on sunbeam-python/sunbeam/core/k8s.py
> +METALLB_ANNOTATION = "metallb.universe.tf/loadBalancerIPs"
This constant is not required as it is replaced with METALLB_IP_NOTATION

2024-12-11 01:42 UTC, hemanthnakkina commented on .github/workflows/test-snap.yml
> +        description: Specify k8s provider
Lets keep this job and remove k8s-provider flag as input.

2024-12-12 01:29 UTC, hemanthnakkina approved these changes

2024-12-12 01:29 UTC, merged